### ISSUE TITLE
polish gpcr_list view

### ISSUE THREAD

**Issue by Amanda-Wakefield** [Amanda-Wakefield/Group_Project#16]
add `class="table-dark"` to `tr` tags with allosteric ligands, add a button to filter by allosteric ligands

**Comment by schifferl** [comment]
allosteric ligands now have a different background (e.g. `5X7D`) in the table, button forthcoming

**Comment by schifferl** [comment]
Oh, I did this to the details page, but I will add it to the list page too

**Comment by schifferl** [comment]
`$("#table").DataTable().row().node().getElementsByTagName("td")[6].innerHTML != "None"`
